Repository harshita214/Chrome-Extension, pull requests merged in 2023-03, with the labels that each got.

#328 Update README.md
  README.md
Labels: JWOC, hard

#327 Updated Latest News Extension
  Interest-Calculator/compund interest/popup.js
  Latest News/1.png
  Latest News/index.html
  Latest News/readme.md
  Latest News/style.css
Labels: JWOC, medium

#334 style
  Birthday-Reminder/style.css
Labels: JWOC, easy

#335 Synonyms Extension added
  Synonym-extension/1.png
  Synonym-extension/2.png
  Synonym-extension/icon.png
  Synonym-extension/manifest.json
  Synonym-extension/readme.md
  Synonym-extension/style.css
  Synonym-extension/synonyms.html
  Synonym-extension/synonyms.js
Labels: JWOC, hard

#339 Updated Cricket Series Extension
  Cricket Series Extension/1.png
  Cricket Series Extension/2.png
  Cricket Series Extension/3.png
  Cricket Series Extension/README.md
  Cricket Series Extension/popup.html
  Cricket Series Extension/style.css
Labels: JWOC, medium

#337 updated css
  Birthday-Reminder/popup.html
  Birthday-Reminder/style.css
Labels: JWOC, medium

#345 update BMI Calculator
  BMI Calculator/index.html
  BMI Calculator/style.css
Labels: JWOC, medium

#349 Updated Income Tax Calculator Extension
  Income_Tax_Calculator/it.html
  Income_Tax_Calculator/style.css
Labels: JWOC, medium

#351 Updated Code
  Helperbird - Toolbox for Chrome/index.html
Labels: JWOC, medium

#353 improved UI
  Age  Calculator/index.html
  Age  Calculator/script.js
  Age  Calculator/style.css
Labels: JWOC, medium

#354 Changed the UI of extension
  Holidays/Holiday.jpeg
  Holidays/styles.css
Labels: JWOC, medium

#355 Updated fonts
  Helperbird - Toolbox for Chrome/styles/fonts/arial.css
  Helperbird - Toolbox for Chrome/styles/fonts/bookman.css
  Helperbird - Toolbox for Chrome/styles/fonts/comic-sans.css
  Helperbird - Toolbox for Chrome/styles/fonts/courier.css
  Helperbird - Toolbox for Chrome/styles/fonts/georgia.css
Labels: JWOC, medium

#340 changing the toogle dark mode button UI
  Dark Mode Extension/appOff.js
  Dark Mode Extension/appOn.js
  Dark Mode Extension/index.html
  Dark Mode Extension/manifest.json
  Dark Mode Extension/script.js
  Dark Mode Extension/style.css
  Dark Mode Extension/styles.css
Labels: JWOC, medium

#360 Changed the UI colours
  Helperbird - Toolbox for Chrome/styles/highlight-menu/theme.css
Labels: JWOC, hard

#362 Made the UI changes
  Birthday-Reminder/Product_sans.ttf
  Birthday-Reminder/popup.html
  Birthday-Reminder/style.css
Labels: JWOC, hard

#366 Stop-Watch Extension added
  stop watch/content.css
  stop watch/content.js
  stop watch/icon128.png
  stop watch/icon16.png
  stop watch/icon48.png
  stop watch/index.html
  stop watch/manifest.json
Labels: JWOC, hard

#364 Updated links to fetch data
  COVID-19 stats/stats.html
Labels: JWOC, medium

#372 Updated QR Generator
  QR-Generator/popup.html
  QR-Generator/script.js
  QR-Generator/style.css
Labels: JWOC, medium

#370 updated UI currency calc
  Alarm clock/alarm.css
  Currency Convertor/popup.html
  Currency Convertor/popup.js
Labels: JWOC, medium

#369 Added new logos and UI changes
  Coding Profile Launcher/Logo-code.png
  Coding Profile Launcher/codechef.png
  Coding Profile Launcher/codeforces.png
  Coding Profile Launcher/github.png
  Coding Profile Launcher/gitlab.png
  Coding Profile Launcher/hackearth.png
  Coding Profile Launcher/hackerrank .png
  Coding Profile Launcher/hackerrank.png
  Coding Profile Launcher/index.html
  Coding Profile Launcher/leetcode.png
  Coding Profile Launcher/style.css
Labels: JWOC, medium

#379 Made the UI Changes
  Weather App/Product Sans Bold.ttf
  Weather App/Product Sans Regular.ttf
  Weather App/background.css
  Weather App/popup.html
  Weather App/script.js
  Weather App/style.css
  Weather App/weatherbackground.png
Labels: JWOC, medium

#377 Sales-Tax Extension Added
  Sales-Tax Calculator/calculate.js
  Sales-Tax Calculator/icon48.png
  Sales-Tax Calculator/index.html
  Sales-Tax Calculator/manifest.json
  Sales-Tax Calculator/style.css
Labels: JWOC, hard

#380 Simon Game Added
  simon game extension/game.js
  simon game extension/icon128.png
  simon game extension/icon16.png
  simon game extension/icon48.png
  simon game extension/index.html
  simon game extension/jquery.min.js
  simon game extension/manifest.json
  simon game extension/sounds/blue.mp3
  simon game extension/sounds/green.mp3
  simon game extension/sounds/red.mp3
  simon game extension/sounds/wrong.mp3
  simon game extension/sounds/yellow.mp3
  simon game extension/styles.css
Labels: JWOC, hard

#382 Added the PNR status Chrome extension
  RailwayPNR/manifest.json
  RailwayPNR/popup.html
  RailwayPNR/popup.js
Labels: JWOC, hard

#386 Hex code Color Generator Added
  Hex code Color generator/hex.js
  Hex code Color generator/icon48.png
  Hex code Color generator/index.html
  Hex code Color generator/manifest.json
  Hex code Color generator/style.css
Labels: JWOC, hard

#385 Made the UI enhancements
  BMI Calculator/Logo-code.png
  BMI Calculator/Product Sans Bold.ttf
  BMI Calculator/Product Sans Regular.ttf
  BMI Calculator/bmi.png
  BMI Calculator/manifest.json
  BMI Calculator/style.css
Labels: JWOC, medium

#388 Temperature Converter Extension Added
  Temperature Converter Extension/icon48.png
  Temperature Converter Extension/index.html
  Temperature Converter Extension/index.js
  Temperature Converter Extension/manifest.json
  Temperature Converter Extension/style.css
Labels: JWOC, medium

#391 Updated Quadratic Equation Calculator
  QR-Generator/style.css
  Quadratic Equation Calculator/1.png
  Quadratic Equation Calculator/2.png
  Quadratic Equation Calculator/popup.html
  Quadratic Equation Calculator/popup.js
  Quadratic Equation Calculator/readme.md
  Quadratic Equation Calculator/style.css
Labels: JWOC, medium

#394 updated the extension
  Currency Convertor/popup.js
Labels: JWOC, medium

#400 Added Image to Colour Palette extension
  Image to Color Palette/index.html
  Image to Color Palette/main.js
  Image to Color Palette/style.css
Labels: JWOC, medium

#406 Updated Links and improved the images
  Anime Director/images/icon128.png
  Anime Director/images/icon64.png
  Anime Director/index.html
Labels: JWOC, medium

#408 Added CSS measurement Converter
  CSS measurement extension/icon48.png
  CSS measurement extension/index.html
  CSS measurement extension/index.js
  CSS measurement extension/manifest.json
  CSS measurement extension/style.css
Labels: JWOC, hard

#414 No-Distraction Extension Added
  NO-Distraction Extension/1.jpg
  NO-Distraction Extension/index.js
  NO-Distraction Extension/manifest.json
Labels: JWOC, hard

#416 Made UI changes
  Say It/Product Sans Bold.ttf
  Say It/Product Sans Regular.ttf
  Say It/logo.png
  Say It/popup.html
  Say It/style.css
Labels: JWOC, medium

#424 Added Overwrite Extension
  Overwrite Extension/icon48.png
  Overwrite Extension/manifest.json
  Overwrite Extension/p5.dom.js
  Overwrite Extension/p5.js
  Overwrite Extension/p5.min.js
  Overwrite Extension/sketch.js
  contrast/_metadata/verified_contents.json
Labels: JWOC, hard

#422 Added currency converter
  Currency Converter/README.md
  Currency Converter/images (1).png
  Currency Converter/index.html
  Currency Converter/main.js
  Currency Converter/manifest.json
  Currency Converter/style.css
Labels: JWOC, hard

#421 added a new extension | Sing along
  Sing_Along/images/ARJ.png
  Sing_Along/images/HMS.png
  Sing_Along/images/HNS.png
  Sing_Along/images/JBN.png
  Sing_Along/images/KK.png
  Sing_Along/images/UDN.png
  Sing_Along/images/style.css
  Sing_Along/index.html
  Sing_Along/manifest.json
Labels: JWOC, hard

#412 Scientific Calculator
  Scientific-Calculator/README.md
  Scientific-Calculator/Screenshot.png
  Scientific-Calculator/img/favicon.png
  Scientific-Calculator/img/icons128.png
  Scientific-Calculator/img/icons16.png
  Scientific-Calculator/img/icons48.png
  Scientific-Calculator/manifest.json
  Scientific-Calculator/popup.html
  Scientific-Calculator/popup.js
  Scientific-Calculator/style.css
Labels: JWOC, medium

#429 Added the Password Generator extension
  Password Generator/logo.png
  Password Generator/manifest.json
  Password Generator/popup.html
  Password Generator/script.js
  Password Generator/style.css
Labels: JWOC, hard

#432 Added the Notepad Extension
  NotePad/README.md
  NotePad/icon.png
  NotePad/manifest.json
  NotePad/popup.html
  NotePad/script.js
Labels: JWOC, hard

#431 Updated Age Calculator
  Age  Calculator/1.png
  Age  Calculator/Readme.md
  Age  Calculator/index.html
  Age  Calculator/script.js
  Age  Calculator/style.css
Labels: JWOC, hard

#426 Added the book selection extension
  Book_suggestion/images/style.css
  Book_suggestion/index.html
  Book_suggestion/manifest.json
  Sing_Along/index.html
Labels: JWOC, hard

#436 Added the youtube save extension
  YoutubeLinksaver/css/editPlaylist.css
  YoutubeLinksaver/css/popup.css
  YoutubeLinksaver/editPlaylist.html
  YoutubeLinksaver/js/background.js
  YoutubeLinksaver/js/editPlaylist.js
  YoutubeLinksaver/js/jquery.min.js
  YoutubeLinksaver/js/playNextVid.js
  YoutubeLinksaver/js/popup.js
  YoutubeLinksaver/logo.png
  YoutubeLinksaver/manifest.json
  YoutubeLinksaver/popup.html
Labels: JWOC, hard

#439 Added word counter extension
  word_counter/app.js
  word_counter/assets/styles/style.css
  word_counter/img.png
  word_counter/index.html
  word_counter/manifest.json
Labels: JWOC, hard

#410 image fixing extension
  imageFixing/_locales/de/messages.json
  imageFixing/_locales/en/messages.json
  imageFixing/_locales/es/messages.json
  imageFixing/_locales/fr/messages.json
  imageFixing/_locales/it/messages.json
  imageFixing/_locales/ja/messages.json
  imageFixing/_locales/ko/messages.json
  imageFixing/_locales/ru/messages.json
  imageFixing/_locales/th/messages.json
  imageFixing/_locales/vi/messages.json
  imageFixing/_locales/zh-CN/messages.json
  imageFixing/background.js
  imageFixing/datas/LICENSE
  imageFixing/datas/public_suffix_list.dat
  imageFixing/doc/ko_KR/README.md
  imageFixing/icons/README.md
  imageFixing/icons/hammer.png
  imageFixing/icons/icons8-gallery-16.png
  imageFixing/icons/icons8-gallery-24.png
  imageFixing/icons/icons8-gallery-32.png
  imageFixing/icons/icons8-gallery-64.png
  imageFixing/manifest.json
  imageFixing/popup/popup.css
  imageFixing/popup/popup.html
  imageFixing/popup/popup.js
Labels: JWOC, hard

#446 Added Ad skip extension
  YoutubeAdSkip/Makefile
  YoutubeAdSkip/manifest.json
  YoutubeAdSkip/skip.png
  YoutubeAdSkip/skipad.js
Labels: JWOC, hard
